/*

 BKG.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 32

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bkg_tilemapBank 0

/* Super Gameboy palette 0 */
#define bkg_tilemapSGBPal0c0 6076
#define bkg_tilemapSGBPal0c1 8935
#define bkg_tilemapSGBPal0c2 6596
#define bkg_tilemapSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bkg_tilemapSGBPal1c0 6076
#define bkg_tilemapSGBPal1c1 8935
#define bkg_tilemapSGBPal1c2 6596
#define bkg_tilemapSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bkg_tilemapSGBPal2c0 6076
#define bkg_tilemapSGBPal2c1 8935
#define bkg_tilemapSGBPal2c2 6596
#define bkg_tilemapSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bkg_tilemapSGBPal3c0 6076
#define bkg_tilemapSGBPal3c1 8935
#define bkg_tilemapSGBPal3c2 6596
#define bkg_tilemapSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bkg_tilemapCGBPal0c0 32767
#define bkg_tilemapCGBPal0c1 32767
#define bkg_tilemapCGBPal0c2 31822
#define bkg_tilemapCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bkg_tilemapCGBPal1c0 32767
#define bkg_tilemapCGBPal1c1 32767
#define bkg_tilemapCGBPal1c2 2495
#define bkg_tilemapCGBPal1c3 0

/* Gameboy Color palette 2 */
#define bkg_tilemapCGBPal2c0 32320
#define bkg_tilemapCGBPal2c1 31710
#define bkg_tilemapCGBPal2c2 32320
#define bkg_tilemapCGBPal2c3 32552

/* Gameboy Color palette 3 */
#define bkg_tilemapCGBPal3c0 32767
#define bkg_tilemapCGBPal3c1 31951
#define bkg_tilemapCGBPal3c2 17417
#define bkg_tilemapCGBPal3c3 0

/* Gameboy Color palette 4 */
#define bkg_tilemapCGBPal4c0 32767
#define bkg_tilemapCGBPal4c1 282
#define bkg_tilemapCGBPal4c2 127
#define bkg_tilemapCGBPal4c3 185

/* Gameboy Color palette 5 */
#define bkg_tilemapCGBPal5c0 6076
#define bkg_tilemapCGBPal5c1 8935
#define bkg_tilemapCGBPal5c2 6596
#define bkg_tilemapCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bkg_tilemapCGBPal6c0 6076
#define bkg_tilemapCGBPal6c1 8935
#define bkg_tilemapCGBPal6c2 6596
#define bkg_tilemapCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bkg_tilemapCGBPal7c0 6076
#define bkg_tilemapCGBPal7c1 8935
#define bkg_tilemapCGBPal7c2 6596
#define bkg_tilemapCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bkg_tilemapCGB[];
/* Start of tile array. */
extern unsigned char bkg_tilemap[];

/* End of BKG.H */
