/*

 COLLISION_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 22 x 18
   Tile set      : F:\EclipseWorkSpaceforC++\GameBoyWorkSapce\�黨СħŮREMIX\res\bkg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 22
#define hudmapHeight 18
#define hudmapBank 0

#define hudmap hudmapPLN0
extern unsigned char hudmapPLN0[];
extern unsigned char hudmapPLN1[];

/* End of COLLISION_MAP.H */
