/*

 HUDMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : intro.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 10
#define hudmapHeight 1
#define hudmapBank 0

#define hudmap hudmapPLN0
unsigned char hudmapPLN0[] =
{
  0x01,0x02,0x03,0x04,0x12,0x03,0x05,0x06,0x07,0x05
};

unsigned char hudmapPLN1[] =
{
  0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};

/* End of HUDMAP.C */
