/*

 HUDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : intro.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudmapWidth 10
#define hudmapHeight 1
#define hudmapBank 0

#define hudmap hudmapPLN0
extern unsigned char hudmapPLN0[];
extern unsigned char hudmapPLN1[];

/* End of HUDMAP.H */
